name: Publish

on:
  push:
    branches: [master]

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip extension
      run: zip -r TimesheetAutomation.zip TimesheetAutomation
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: TimesheetAutomation.zip
        extension-id: debngnappjjakbkdhgpfaalipidjkgbj
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        publish: false  
